#!/usr/local/zsh

export ALTERNATE_EDITOR=""
export EDITOR="emacsclient -a emacs -t"  # $EDITOR should open in terminal
export VISUAL="emacsclient -a emacs -c " # $VISUAL opens in GUI with non-daemon as alternate

alias e="$HOME/bin/emacsclient.sh"
alias t="$EDITOR"

export PATH=~/.local/bin:$PATH
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

# added by newengsetup
type "brew" &>/dev/null && export PATH=$(brew --prefix)/sbin:$(brew --prefix)/bin:$PATH

export PATH=$HOME/bin:$PATH

[ -s "/usr/local/bin/virtualenvwrapper.sh" ] && . /usr/local/bin/virtualenvwrapper.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
