#!/usr/bin/env bash
# Temporarily override global DNS with the DHCP-provided DNS from the active interface.
# Restores original settings on exit (Ctrl+C or 'enter').
set -euo pipefail

# Find the primary network interface (first routable, non-tailscale link)
IFACE=$(networkctl list --no-legend | awk '$4 == "routable" && $2 !~ /tailscale/ {print $2; exit}')

if [[ -z "$IFACE" ]]; then
    echo "Error: no routable interface found"
    exit 1
fi

# Get DHCP-provided DNS servers for the interface
mapfile -t DHCP_DNS < <(resolvectl dns "$IFACE" | sed 's/.*: //' | tr ' ' '\n' | grep -v '^$')

if [[ ${#DHCP_DNS[@]} -eq 0 ]]; then
    echo "Error: no DHCP DNS servers found on $IFACE"
    exit 1
fi

echo "Interface: $IFACE"
echo "DHCP DNS:  ${DHCP_DNS[*]}"

# Save current global DNS (may be empty)
ORIG_GLOBAL=$(resolvectl dns | head -1 | sed 's/.*: //' | sed 's/^ *$//')

# Drop-in file to set global DNS
DROPIN="/etc/systemd/resolved.conf.d/99-temp-dhcp-dns.conf"

restore() {
    echo ""
    echo "Restoring original DNS..."
    sudo rm -f "$DROPIN"
    sudo systemctl restart systemd-resolved
    echo "Restored. Current DNS:"
    resolvectl dns
}
trap restore EXIT

# Write temporary drop-in
sudo tee "$DROPIN" > /dev/null <<EOF
# Temporary: use DHCP-provided DNS globally
# Auto-generated by use-dhcp-dns.sh — will be removed on exit
[Resolve]
DNS=${DHCP_DNS[*]}
FallbackDNS=
EOF

sudo systemctl restart systemd-resolved

echo ""
echo "Global DNS now set to: ${DHCP_DNS[*]}"
resolvectl dns
echo ""
echo "Press Enter or Ctrl+C to restore original DNS..."
read -r
